---
abstract: 'API Client for mackerel.io'
author:
  - 'Tatsuro Hisamori <myfinder@cpan.org>'
build_requires:
  Test::Double: '0.05'
  Test::Fatal: '0.013'
  Test::More: '0.98'
configure_requires:
  Module::Build::Tiny: '0.035'
dynamic_config: 0
generated_by: 'Minilla/v2.2.0, CPAN::Meta::Converter version 2.142690'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: WebService-Mackerel
no_index:
  directory:
    - t
    - xt
    - inc
    - share
    - eg
    - examples
    - author
    - builder
provides:
  WebService::Mackerel:
    file: lib/WebService/Mackerel.pm
    version: '0.01'
requires:
  HTTP::Tiny: '0.050'
  JSON: '2.90'
  perl: '5.008001'
resources:
  bugtracker: https://github.com/myfinder/webservice-mackerel/issues
  homepage: https://github.com/myfinder/webservice-mackerel
  repository: git://github.com/myfinder/webservice-mackerel.git
version: '0.01'
x_contributors:
  - 'Tatsuro Hisamori <medianetworks@gmail.com>'
